Gunti28/Billing_Management_System

- pom.xml
- src/main/java/com/srnrit/BMS/controller/UserController.java
- src/main/java/com/srnrit/BMS/dao/UserDao.java
- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
- src/main/java/com/srnrit/BMS/dto/UserRequestDTO.java
- src/main/java/com/srnrit/BMS/dto/UserResponseDTO.java
- src/main/java/com/srnrit/BMS/entity/User.java
- src/main/java/com/srnrit/BMS/exception/userexceptions/UserNotFoundException.java
- src/main/java/com/srnrit/BMS/globalexcepiton/GlobalExceptionHandler.java
- src/main/java/com/srnrit/BMS/mapper/DTOToEntity.java
- src/main/java/com/srnrit/BMS/mapper/EntityToDTO.java
- src/main/java/com/srnrit/BMS/repository/UserRepository.java
- src/main/java/com/srnrit/BMS/service/UserService.java
- src/main/java/com/srnrit/BMS/service/impl/UserServiceImpl.java
- src/main/java/com/srnrit/BMS/util/idgenerator/UserIdGenerator.java
Added basic structure of each package.
> first commit by adding basic structure of the bms project

- src/main/java/com/srnrit/BMS/entity/Category.java
- src/main/java/com/srnrit/BMS/util/idgenerator/CategoryIdGenerator.java
I am done Entity class and CategoryidGenerator once check the code
> Category class and CategoryIdGenerator once check Abubakar

- src/main/java/com/srnrit/BMS/dto/UserRequestDTO.java
- src/main/java/com/srnrit/BMS/dto/UserResponseDTO.java
- src/main/java/com/srnrit/BMS/mapper/DTOToEntity.java
- src/main/java/com/srnrit/BMS/mapper/EntityToDTO.java
Now i added Serializable interface into both UserRequestDTO and UserResponseDTO
> implemented serializable 

- pom.xml
- src/main/java/com/srnrit/BMS/controller/UserController.java
- src/main/java/com/srnrit/BMS/dao/ProductDao.java
- src/main/java/com/srnrit/BMS/dao/UserDao.java
- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
- src/main/java/com/srnrit/BMS/dto/UserRequestDTO.java
- src/main/java/com/srnrit/BMS/dto/UserResponseDTO.java
- src/main/java/com/srnrit/BMS/entity/Product.java
- src/main/java/com/srnrit/BMS/entity/User.java
- src/main/java/com/srnrit/BMS/exception/userexceptions/UserNotFoundException.java
- src/main/java/com/srnrit/BMS/globalexcepiton/GlobalExceptionHandler.java
- src/main/java/com/srnrit/BMS/mapper/DTOToEntity.java
- src/main/java/com/srnrit/BMS/mapper/EntityToDTO.java
- src/main/java/com/srnrit/BMS/repository/ProductRepository.java
- src/main/java/com/srnrit/BMS/repository/UserRepository.java
- src/main/java/com/srnrit/BMS/service/UserService.java
- src/main/java/com/srnrit/BMS/service/impl/UserServiceImpl.java
- src/main/java/com/srnrit/BMS/util/idgenerator/ProductIdGenerator.java
- src/main/java/com/srnrit/BMS/util/idgenerator/UserIdGenerator.java
- src/main/resources/application.properties
Created Product Entity, Product Id Generator, Product Repository and Product Dao Interface....As well as changed application.properties(Added Oracle  and hibernate properties a ) and pom.xml(Added Oracle Driver)
> ProductDao Layer

- src/main/java/com/srnrit/BMS/entity/User.java
- src/main/java/com/srnrit/BMS/util/idgenerator/UserIdGenerator.java
Changes made in UserEntity Class and created UserId Generator .
> UserIdGenerator,UserEntity

- src/main/java/com/srnrit/BMS/service/UserService.java
- src/main/java/com/srnrit/BMS/service/impl/UserServiceImpl.java
Created UserService interface and UserServiceImpl Implementation Class
> Added Basic Structure Of User Service Layer

- pom.xml
- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
- src/main/java/com/srnrit/BMS/dto/CategoryRequestDTO.java
- src/main/java/com/srnrit/BMS/dto/CategoryResponseDTO.java
- src/main/java/com/srnrit/BMS/dto/UserRequestDTO.java
- src/main/java/com/srnrit/BMS/entity/Category.java
- src/main/java/com/srnrit/BMS/repository/CategoryRepository.java
- src/main/java/com/srnrit/BMS/service/ICategoryService.java
- src/main/java/com/srnrit/BMS/service/impl/CategoryServiceImpl.java
- src/main/java/com/srnrit/BMS/service/impl/UserServiceImpl.java
- src/main/resources/application.properties
I created CategoryRequestDTO,CategoryResponseDTO,CategoryRepository,added validation dependency in pom.xml file
> Category module

- pom.xml
- src/main/java/com/srnrit/BMS/dao/UserDao.java
- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
- src/main/java/com/srnrit/BMS/exception/userexceptions/UserNotFoundException.java
- src/main/java/com/srnrit/BMS/exception/userexceptions/UserNotcreatedException.java
- src/main/java/com/srnrit/BMS/globalexcepiton/GlobalExceptionHandler.java
- src/main/java/com/srnrit/BMS/repository/UserRepository.java
- src/main/java/com/srnrit/BMS/util/Message.java
- src/main/java/com/srnrit/BMS/util/idgenerator/UserIdGenerator.java
- src/main/resources/application.properties
- src/test/java/com/srnrit/BMS/BmsApplicationTests.java
I added User repository class and In userDao interface create saveuser() method and deleteUser() method and create UserDAOImpl to implemet those methods.
> Add UserRepository,UserDAo and UserDAOImpl and add one test case on saveUser

- src/main/java/com/srnrit/BMS/service/impl/UserServiceImpl.java
- src/main/resources/application.properties
- src/test/java/com/srnrit/BMS/BmsApplicationTests.java
i created one saveUser() method in userServceImpl imlementation class and i done unit testing also to saveUser()
check it approve my code and merge to Team_Hulk
> added saveUser() method and one unit test saveUserService method

- pom.xml
- src/main/java/com/srnrit/BMS/controller/UserController.java
- src/main/java/com/srnrit/BMS/dto/UserRequestDTO.java
- src/main/java/com/srnrit/BMS/globalexcepiton/GlobalExceptionHandler.java
- src/main/java/com/srnrit/BMS/util/idgenerator/UserIdGenerator.java
- src/main/resources/application.properties
Basicaly i createUser handler method taking json and converting to UserRequestDTO and validating each data and if it is a valid DTO then sending to user service layer.And if dto having some exception then it will send error response .
> Created createUser api for registering the user.

- src/main/java/com/srnrit/BMS/dto/UserResponseDTO.java
- src/main/java/com/srnrit/BMS/mapper/DTOToEntity.java
- src/test/java/com/srnrit/BMS/BmsApplicationTests.java
Basicaly i createUser handler method taking json and converting to UserRequestDTO and validating each data and if it is a valid DTO then sending to user service layer.And if dto having some exception then it will send error response . And changed in DTOToEntity class .
> changes in UserResponseDTO and DTOToEntity

- pom.xml
- src/main/java/com/srnrit/BMS/controller/CategoryController.java
- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
- src/main/java/com/srnrit/BMS/dto/CategoryRequestDTO.java
- src/main/java/com/srnrit/BMS/dto/CategoryResponseDTO.java
- src/main/java/com/srnrit/BMS/dto/UserRequestDTO.java
- src/main/java/com/srnrit/BMS/entity/Category.java
- src/main/java/com/srnrit/BMS/entity/Product.java
- src/main/java/com/srnrit/BMS/repository/CategoryRepository.java
- src/main/java/com/srnrit/BMS/service/ICategoryService.java
- src/main/java/com/srnrit/BMS/service/impl/CategoryServiceImpl.java
- src/main/java/com/srnrit/BMS/service/impl/UserServiceImpl.java
- src/main/resources/application.properties
> Update 002 resolving conflict

- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
- src/main/java/com/srnrit/BMS/service/UserService.java
- src/main/java/com/srnrit/BMS/service/impl/UserServiceImpl.java
- src/test/java/com/srnrit/BMS/BmsApplicationTests.java
i added deletedUserById in UserService interface and provided implementation to that delete method in UserServiceImpl class, and along with unit testing method also created for deleteUser...check it and approve
> added deletedUserById method along with unit testing for this method

- src/main/java/com/srnrit/BMS/dao/UserDao.java
- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
- src/main/java/com/srnrit/BMS/exception/userexceptions/UserAleadyExistException.java
- src/test/java/com/srnrit/BMS/BmsApplicationTests.java
Added these methods findByUserId(String userId), updateByUserId(User user, String userId), findByUserEmail(String userEmail), findByUserPhoneNumber(long userPhoneNumber) in UserDAOImpl Layer.
> Add changes in UserDaoImpl layer w

- src/main/java/com/srnrit/BMS/dto/CategoryRequestDTO.java
- src/main/java/com/srnrit/BMS/entity/Category.java
- src/main/java/com/srnrit/BMS/service/ICategoryService.java
- src/main/java/com/srnrit/BMS/service/impl/CategoryServiceImpl.java
Added in category class add product and remove product ..
> Category madule

- src/main/java/com/srnrit/BMS/dao/impl/ProductDaoImpl.java
- src/main/java/com/srnrit/BMS/dto/ProductRequestDTO.java
- src/main/java/com/srnrit/BMS/dto/ProductResponseDTO.java
- src/main/java/com/srnrit/BMS/exception/productexceptions/ProductNotCreatedException.java
- src/main/java/com/srnrit/BMS/exception/productexceptions/ProductNotFoundException.java
In Product DTO created productResponse class and productRequestclass...
In Product Exceptions created productnotcreatedException class and productnotfoundException
Done some modifations on ProductDaoImplementation
> Created Product DTO and Exceptions

- src/main/java/com/srnrit/BMS/controller/UserController.java
- src/main/java/com/srnrit/BMS/service/UserService.java
- src/main/java/com/srnrit/BMS/service/impl/UserServiceImpl.java
- src/test/java/com/srnrit/BMS/BmsApplicationTests.java
i added UpdatedUserById  abstract method in UserService interface and Provided implementation in UserServiceImpl implementation class..
> added UpdatedUserById method in UserServiceImpl class

- src/main/java/com/srnrit/BMS/dao/UserDao.java
- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
Added loginByUserEmailAndPasword() method in UserDAo layer.
> chaanges in UserDAo layer

- src/main/java/com/srnrit/BMS/controller/UserController.java
- src/main/java/com/srnrit/BMS/globalexcepiton/GlobalExceptionHandler.java
- src/main/java/com/srnrit/BMS/service/impl/UserServiceImpl.java
- src/test/java/com/srnrit/BMS/BmsApplicationTests.java
DeleteUserById api is taking userId and based upon id it is deleting the user .
FindUserById api is taking userId and giving onr UserResponseDTO if userId is found.
Both the api handles all exception regarding on userId.
> DeleteUserById and FindUserById api

- src/main/java/com/srnrit/BMS/service/impl/UserServiceImpl.java
- src/main/resources/application.properties
i added some changes in service implementation class
> added some changes in service implementation class

- src/main/java/com/srnrit/BMS/dto/LoginRequestDTO.java
LoginRequestDto class will take the email and password from the json for user login purpose with all validation.And exception also regarding the input .
> LoginRequestDto class 

- src/main/java/com/srnrit/BMS/dao/UserDao.java
- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
- src/main/java/com/srnrit/BMS/globalexcepiton/GlobalExceptionHandler.java
- src/main/java/com/srnrit/BMS/util/FileStorageProperties.java
- src/main/java/com/srnrit/BMS/util/idgenerator/ImageFileNameGenerator.java
- src/main/resources/application.properties
- src/test/java/com/srnrit/BMS/BmsApplicationTests.java
Added IllegalArgumentException handler and UserAlreadyExistExcpetion handler in GlobalExcpetions.
> modified in GlobalExcpetion

- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
Modified in loginByUserEmailAndpassword() method in UserDaoimpl class.
> modified in UserDAOimpl class

- src/main/java/com/srnrit/BMS/service/UserService.java
- src/main/java/com/srnrit/BMS/service/impl/UserServiceImpl.java
- src/test/java/com/srnrit/BMS/BmsApplicationTests.java
i modify some chnages in service layer layer
> added some changes in BMs Project

- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
- src/main/java/com/srnrit/BMS/exception/userexceptions/UnSupportedFileTypeException.java
- src/main/java/com/srnrit/BMS/globalexcepiton/GlobalExceptionHandler.java
- src/main/java/com/srnrit/BMS/repository/UserRepository.java
- src/main/java/com/srnrit/BMS/util/FileStorageProperties.java
- src/main/java/com/srnrit/BMS/util/idgenerator/ImageFileNameGenerator.java
adding global exception and userExceptiion and modify in loginByUserEmailAndPassword() method.
> add changes in globalException, userDaoImpl

- src/main/java/com/srnrit/BMS/service/impl/UserServiceImpl.java
- src/test/java/com/srnrit/BMS/BmsApplicationTests.java
i added LoginByEmailAndPassword abstract method in UserService interface and provided method implementation in UserServiceImpl class and also unit test case
> added LoginByEmailAndPassword method in userServiceImpl class

- src/main/java/com/srnrit/BMS/util/FileStorageProperties.java
- src/main/resources/application.properties
Add some changes in Fileproperties.
> modify in Fileproperties

- src/main/java/com/srnrit/BMS/service/UserService.java
- src/main/java/com/srnrit/BMS/service/impl/UserServiceImpl.java
i added editUserImage in UserService interface and provided method implementation to abstact method ..
> added Edit Image method in UserServiceImpl class

- src/main/java/com/srnrit/BMS/dao/UserDao.java
- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
Adding implementation for findAllusers() in UserDaoImpl class .
> modification in UserDao and UserDaoimpl classes

- src/main/java/com/srnrit/BMS/controller/CategoryController.java
Completed the Controller layer of Category
> Category Module 

- src/main/java/com/srnrit/BMS/repository/UserRepository.java
- src/main/java/com/srnrit/BMS/util/FileStorageProperties.java
modified in FileStorageProperties
> modified in FileStorageProperties

- src/main/java/com/srnrit/BMS/service/UserService.java
- src/main/java/com/srnrit/BMS/service/impl/UserServiceImpl.java
- src/test/java/com/srnrit/BMS/BmsApplicationTests.java
added some changes in service impl class
> added some changes in service impl class

- src/main/java/com/srnrit/BMS/controller/UserController.java
Added Fetcha allUsers()in UserController .
> UserController

- src/main/java/com/srnrit/BMS/dao/UserDao.java
- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
Adding changePassword() method in UserDAO layer.
> adding changePassword() method

- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
> adding findByEmail() method

- src/main/java/com/srnrit/BMS/dto/EmailRequestDTO.java
EmailRequestDTO is taking email for validating the user email.
> added EmailRequestDTO in dto package

- src/main/java/com/srnrit/BMS/dto/EmailRequestDTO.java
just added lombok annotation in EmailRequestDTO for getting all getter,setter ,toString  and constructor.
> adding lombok annotation in EmailRequestDTO

- src/main/java/com/srnrit/BMS/controller/ProductController.java
- src/main/java/com/srnrit/BMS/dto/ProductRequestDTO.java
- src/main/java/com/srnrit/BMS/globalexcepiton/GlobalExceptionHandler.java
- src/main/java/com/srnrit/BMS/util/idgenerator/ProductImageFileNameGenerator.java
> Image Validation added

- src/main/java/com/srnrit/BMS/dto/ProductRequestDTO.java
- src/test/java/com/srnrit/BMS/controller/ProductControllerTest.java
- src/test/java/com/srnrit/BMS/dao/ProductDaoTest.java
- src/test/java/com/srnrit/BMS/service/ProductServiceTest.java
> Added packages for JUNIT TESTING

- src/main/java/com/srnrit/BMS/dto/ChangePasswordRequestDTO.java
- src/main/java/com/srnrit/BMS/service/UserService.java
- src/main/java/com/srnrit/BMS/service/impl/UserServiceImpl.java
- src/main/java/com/srnrit/BMS/util/EmailSender.java
- src/main/java/com/srnrit/BMS/util/OTPOperation.java
- src/main/java/com/srnrit/BMS/util/idgenerator/OTPGenerator.java
- src/main/resources/application.properties
- src/test/java/com/srnrit/BMS/BmsApplicationTests.java
added some methods  and  classes in dto packages modification in service layer
> added some methods and modification in service layer

- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
- src/test/java/com/srnrit/BMS/BmsApplicationTests.java
Adding Test cases in BMSTestApplication and add some modified in UserDaoImpl
> adding some changes in UserDaoimpl and testCases

- src/main/java/com/srnrit/BMS/controller/UserController.java
- src/test/java/com/srnrit/BMS/userdao/UserDAOTestCases.java
Adding deleteUserbyId() testcase and UpdateUserByid() test cases in UserDaotestCases class.
> aading userTestcases

- src/test/java/com/srnrit/BMS/userservicetest/UserServiceTestCases.java
> just commiting

- src/main/java/com/srnrit/BMS/controller/UserController.java
- src/main/java/com/srnrit/BMS/dto/UpdateUserRequestDTO.java
- src/main/java/com/srnrit/BMS/runners/DatabaseInitializer.java
- src/main/resources/application.properties
Added one DataBase Intializer runner .It is responsible to create require table, sequence ,once before starting the application.
> DatabaseIntializer runner

- src/main/java/com/srnrit/BMS/globalexcepiton/GlobalExceptionHandler.java
- src/test/java/com/srnrit/BMS/dao/ProductDaoImplTest.java
> Done Product DAO JUNIT

- src/main/java/com/srnrit/BMS/dao/impl/ProductDaoImpl.java
- src/main/java/com/srnrit/BMS/globalexcepiton/GlobalExceptionHandler.java
- src/main/java/com/srnrit/BMS/repository/ProductRepository.java
Here I added validations , once have a look on that!!!
> Added validation for duplicate product names

- src/main/java/com/srnrit/BMS/globalexcepiton/GlobalExceptionHandler.java
- src/main/resources/application.properties
> Modified GLOBAL EXCEPTION

- src/main/java/com/srnrit/BMS/controller/UserController.java
- src/main/java/com/srnrit/BMS/service/impl/UserServiceImpl.java
- src/test/java/com/srnrit/BMS/BmsApplicationTests.java
added some mofications in service impl class
> added some mofications in service impl class

- src/main/java/com/srnrit/BMS/controller/UserController.java
- src/main/java/com/srnrit/BMS/dto/LoginRequestDTO.java
- src/main/java/com/srnrit/BMS/globalexcepiton/GlobalExceptionHandler.java
- src/test/java/com/srnrit/BMS/controllertest/UserControllerTest.java
Just changing  msg to Message json  for response in deleteUser handler method.
> changes in usercontroller delete api method

- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
- src/test/java/com/srnrit/BMS/userdaotest/UserDAOTest.java
deleteing setPassword field in userDaoImpl class.
> nothing to modify

- src/main/java/com/srnrit/BMS/dto/UpdateUserRequestDTO.java
- src/main/java/com/srnrit/BMS/entity/User.java
removing two forward slashes in UpdateUserRequestDTO in userEmail validation field.
> changed in UpdateUserRequestDTO

- src/main/java/com/srnrit/BMS/dao/UserDao.java
- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
- src/test/java/com/srnrit/BMS/userdaotest/UserDAOTest.java
- src/test/java/com/srnrit/BMS/userdaotest/UserRepositoryTest.java
adding test cases for userDaoImpl class and UserRepository class and in userDaoImpl class add the UpdateByUserId() method.
> adding userdaotest and userRepository test and userdaoimpl class in modify in  UpdateUserById

- src/test/java/com/srnrit/BMS/userdaotest/UserDAOTest.java
- src/test/java/com/srnrit/BMS/userdaotest/UserRepositoryTest.java
uncommenting the code only test case classes.
> removing comments

- pom.xml
- src/main/java/com/srnrit/BMS/dao/impl/CategoryDaoImpl.java
- src/test/java/com/srnrit/BMS/dao/CategoryDAOTest.java
- src/test/java/com/srnrit/BMS/service/CategoryServiceTest.java
> Added test cases in DAO layer

- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
- src/test/java/com/srnrit/BMS/userdaotest/UserDAOTest.java
> changes in updateById in USerDAoImpl class

- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
>  added one flag variable in updateUserById() method of UserDaoImpl

- pom.xml
- src/main/java/com/srnrit/BMS/runners/ProductDatabaseInitializer.java
- src/test/java/com/srnrit/BMS/service/ProductServiceTest.java
See , I added PRODUCT DATABASE INITIALIZER class in  runners  package (which are used to ..not create sequence in DB ..so it would better to create in JAVA PRGM itself ) and also added some more test cases in ServiceTest
> Added runners and added Test cases in service Test

- pom.xml
- src/main/java/com/srnrit/BMS/dao/impl/ProductDaoImpl.java
- src/main/resources/application.properties
- src/test/java/com/srnrit/BMS/dao/ProductDaoImplTest.java
Added more testcases in productDaoImpl test and make some changes in productDaoImpl class and added some plugins and dependency for junit testing and changed my database properties in application properties....
> Added more Test cases

- pom.xml
- src/main/java/com/srnrit/BMS/service/impl/UserServiceImpl.java
- src/test/java/com/srnrit/BMS/userservicetest/UserServiceTestCases.java
added 20 test cases for service layer
>  added some test cases for service layer

- pom.xml
- src/main/java/com/srnrit/BMS/controller/UserController.java
- src/main/java/com/srnrit/BMS/dto/ChangePasswordRequestDTO.java
- src/main/java/com/srnrit/BMS/dto/EmailRequestDTO.java
- src/main/java/com/srnrit/BMS/dto/LoginRequestDTO.java
- src/main/java/com/srnrit/BMS/dto/UpdateUserRequestDTO.java
- src/main/java/com/srnrit/BMS/dto/UserRequestDTO.java
- src/main/java/com/srnrit/BMS/globalexcepiton/GlobalExceptionHandler.java
- src/main/java/com/srnrit/BMS/runners/DatabaseInitializer.java
- src/test/java/com/srnrit/BMS/controllertest/UserControllerTest.java
Lot of changes in dto classes and GlobalExceptionHandler class and DatabaseIntializer class and UserController class
> chages in classes

- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
- src/main/java/com/srnrit/BMS/repository/UserRepository.java
- src/main/java/com/srnrit/BMS/util/idgenerator/ImageFileNameGenerator.java
- src/test/java/com/srnrit/BMS/userdaotest/UserDAOTest.java
- src/test/java/com/srnrit/BMS/userdaotest/UserRepositoryTest.java
Added some test cases on editImage() method in UserdaoTest class.
> adding some test cases on editImage() method

- src/test/java/com/srnrit/BMS/userservicetest/UserServiceTestCases.java
modifications in service Test case
> modifications in service Test case

- pom.xml
- src/main/java/com/srnrit/BMS/dao/impl/UserDaoImpl.java
- src/test/java/com/srnrit/BMS/userdaotest/UserDAOTest.java
> adding Test cases in UserDao Class

- pom.xml
- src/main/java/com/srnrit/BMS/service/impl/UserServiceImpl.java
- src/main/resources/application.properties
- src/test/java/com/srnrit/BMS/userservicetest/UserServiceTestCases.java
i removed warnings in service layer
> removing warnings in service layer

- src/main/java/com/srnrit/BMS/entity/User.java
> increasing Email length is change in User entity class

- src/main/java/com/srnrit/BMS/controller/CategoryController.java
- src/main/java/com/srnrit/BMS/dao/impl/CategoryDaoImpl.java
- src/main/java/com/srnrit/BMS/entity/Category.java
- src/main/java/com/srnrit/BMS/service/impl/CategoryServiceImpl.java
added input and out request json format in controller layer
> changes in controller layer

- src/test/java/com/srnrit/BMS/userdaotest/UserDAOTest.java
- src/test/java/com/srnrit/BMS/userdaotest/UserRepositoryTest.java
some changes in UserDaoTest class
> Adding EditImage test case

- pom.xml
- src/test/java/com/srnrit/BMS/controllertest/UserControllerTest.java
Adding test cases for UserController apis inside UserControllerTest class
> resolving conflicts and added some test cases regarding on UserController class

- src/test/java/com/srnrit/BMS/userservicetest/UserServiceTest.java
> changed user service test cases

- src/main/java/com/srnrit/BMS/service/impl/ProductServiceImpl.java
- src/test/java/com/srnrit/BMS/service/ProductServiceTest.java
> Added test cases in ProductServiceTest through Impl for Improving the code coverage of Jacaco 
